plugins {
    id 'symera.plugins.extension' apply false
}

ext {
    extName = 'Doramasflix'
    extClass = '.DoramasflixFactory'
    extVersionCode = 9
}

apply plugin: "symera.plugins.extension"

dependencies {
    implementation(project(':lib:fkplayer'))
    implementation(project(':lib-multisrc:pelisplus'))
}
